# Generated by Django 3.2.6 on 2021-08-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='password',
            new_name='isiKonten',
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='email',
            new_name='judulKonten',
        ),
    ]
