# Generated by Django 3.2.6 on 2021-08-23 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_rename_judulkonten_meetup_jeniskonten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='isiKonten',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='jenisKonten',
        ),
        migrations.AddField(
            model_name='meetup',
            name='genreKonten',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='judulKonten',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 9, 49, 59, 217789, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
